//
//  Phase2.swift
//  Instell 10
//
//  Created by HoonieMac on 2020/12/01.
//

import Foundation


var phase2 = [
    Story(imageName: "2-1-0-1", dday: "D-100", title: "학년부장", id: "2-1-0-1", nextId: "2-1-0-2", text: "“지원학과를 바꾸는 편이 좋겠구나.”", action: .text, gif: "2-1-0-1"),
    Story(imageName: "2-1-0-2", dday: "D-100", title: "나", id: "2-1-0-2", nextId: "2-1-0-3", text: "…이게 무슨 말이지?", action: .text),
    Story(imageName: "2-1-0-3", dday: "D-100", title: "나", id: "2-1-0-3", nextId: "2-1-0-4", text: "자소서도 다 완성되었는데,\n수능 100일 남은 고3을 불러놓고 하는 이야기가\n지망학과를 바꾸라고?", action: .text),
    Story(id: "2-1-0-4", action: .choice, question: "자소서도 다 완성되었는데, 수능 100일 남은 고3을 불러놓고 하는 이야기가 지망학과를 바꾸라고?", choices: ["화를 내며 나의 의사를 명확히 밝힌다": "2-1-0-5", "일단 침착하게 이유를 묻는다": "2-1-0-5"]),
    Story(imageName: "2-1-0-5", dday: "D-100", title: "학년부장", id: "2-1-0-5", nextId: "2-1-0-6", text: "“선생님들 사이에서 소통이 잘 안된 거 같더구나.\n이번에 수시 쓰는 학생들 목록을 다시 정리하면서 알게 되었는데,\n네 성적이 컴퓨터공학과를 쓰기엔 부족하더라고.”", action: .text),
    Story(imageName: "2-1-0-6", dday: "D-100", title: "학년부장", id: "2-1-0-6", nextId: "2-1-0-7", text: "“일이 이렇게 되어서 정말 안타까운데, 어쩌겠니.\n대학에 붙으려면 지망학과를 다시 조정해야지.”", action: .text),
    Story(imageName: "2-1-0-7", dday: "D-100", title: "나", id: "2-1-0-7", nextId: "2-1-0-8", text: "“성적이 얼마나 부족한건데요?\n상위권 학생들 중에 서운대 컴퓨터공학과를 쓰겠다는 학생은 저 혼자인걸로 아는데요?”", action: .text),
    Story(imageName: "2-1-0-8", dday: "D-100", title: "학년부장", id: "2-1-0-8", nextId: "2-1-0-9", text: "“자세한 건 또 다른 학생의 개인적인 사항이라 말해줄 수 없고”", action: .text, gif: "2-1-0-8", sound: "당황"),
    Story(imageName: "2-1-0-9", dday: "D-100", title: "학년부장", id: "2-1-0-9", nextId: "2-1-0-10", text: "“그렇지만 분명한 건 너보다 그 학생의 수학 내신이 더 뛰어난데,\n너도 알다시피 컴공이 수학성적을 워낙 중시하잖냐”", action: .text),
    Story(imageName: "2-1-0-10", dday: "D-100", id: "2-1-0-10", nextId: "2-1-0-11", text: "그런 애가 있던가..?", action: .text),
    Story(imageName: "2-1-0-11", dday: "D-100", id: "2-1-0-11", nextId: "2-1-0-12", text: "아무리 그래도 지금 수시 지망학과를 바꾸는 건 리스크가 크다.\n수시 서류접수 시작이 한 달 밖에 안 남았는데...", action: .text),
    Story(imageName: "2-1-0-12", dday: "D-100", title: "나", id: "2-1-0-12", nextId: "2-1-0-13", text: "“선생님, 아무리 그래도 서류접수까지 시간이 얼마 없는데요,\n성적 차이가 큰 게 아니면 그냥 컴공 쓸게요.\n원래도 가고 싶었고요.”", action: .text),
    Story(imageName: "2-1-0-13", dday: "D-100", title: "학년부장", id: "2-1-0-13", nextId: "2-1-0-14", text: "“선생님이 네 생각해서 다른 학생 성적도 이렇게 몰래 알려주는 건데!\n내가 고3 수시 지도를 몇 년을 했는데!”", action: .text, sound: "화남1"),
    Story(imageName: "2-1-0-14", dday: "D-100", title: "학년부장", id: "2-1-0-14", nextId: "2-2-0-1", text: "“선생님이 다 너 잘되라고 하는 소리 아니니!\n너 어차피 컴공 써도 수학 내신에서 밀려서 면접도 못 가!”", action: .text, gif: "2-1-0-14"),
    Story(imageName: "2-2-0-1", dday: "D-100", id: "2-2-0-1", nextId: "2-2-0-2", text: "이제와서 지망학과를 바꾸라니..", action: .text, gif: "2-2-0-1"),
    Story(imageName: "2-2-0-2", dday: "D-100", id: "2-2-0-2", nextId: "2-2-0-3", text: "그런데 나보다 수학 내신을 잘 본 애가 있다니,\n정말 학주 말처럼 면접장에도 못 가보고 떨어지는 걸까?", action: .text, sound: "울음2"),
    Story(imageName: "2-2-0-3", dday: "D-100", id: "2-2-0-3", nextId: "2-2-0-4", text: "내가 1학기에 친구 문제로 수학 공부를 너무 소홀히 했나봐.\n바보같이…", action: .text),
    Story(imageName: "2-2-0-4", dday: "D-100", title: "조력자 1", id: "2-2-0-4", nextId: "2-2-0-5", text: "“어머! 땡떙아! 너 울어?”", action: .text),
    Story(imageName: "2-2-0-5", dday: "D-100", title: "나", id: "2-2-0-5", nextId: "2-2-0-6", text: "“어, 아니야…”", action: .text),
    Story(imageName: "2-2-0-6", dday: "D-100", title: "조력자 1", id: "2-2-0-6", nextId: "2-2-0-7", text: "“왜 그래..ㅠ 무슨 일이야?”", action: .text),
    Story(imageName: "2-2-0-7", dday: "D-100", id: "2-2-0-7", nextId: "2-2-0-8", text: "대충 얼버무리려 하는데, 갑자기 생각났다.\n조력자 1이 마당발이라는 사실이.", action: .text),
    Story(imageName: "2-2-0-8", dday: "D-100", title: "나", id: "2-2-0-8", nextId: "2-2-0-9", text: "”너.. 혹시 이번에 서운대 컴공 지원하는 사람,\n나 말고 또 누구 있는지 알아…?”", action: .text),
    Story(imageName: "2-2-0-9", dday: "D-100", title: "조력자 1", id: "2-2-0-9", nextId: "2-2-0-10", text: "”야, 거길 너 말고 누가 쓰겠니, 입결이 그렇게 높은데.\n암튼 너 공부 잘하는 건 좀 멋있어”", action: .text),
    Story(imageName: "2-2-0-10", dday: "D-100", title: "나", id: "2-2-0-10", nextId: "2-2-0-11", text: "”그렇구나..ㅎ 고마워”\n\n얘도 모르나보네", action: .text),
    Story(imageName: "2-2-0-11", dday: "D-100", title: "조력자 1", id: "2-2-0-11", nextId: "2-2-0-12", text: "”어! 근데 엊그제 급식실에서 박동훈이 자기 컴공으로 돌렸다고,\n막 자랑하던거 들었던 거 같기도 하고…”", action: .text),
    Story(imageName: "2-2-0-12", dday: "D-100", id: "2-2-0-12", nextId: "2-2-0-13", text: "동훈? 박동훈? 운영위원장 아들?\n걔가 수학을 그렇게 잘했어?", action: .text),
    Story(imageName: "2-2-0-13", dday: "D-100", title: "조력자 1", id: "2-2-0-13", nextId: "2-2-0-14", text: "“아! 맞네맞네! 걔가 자기 저번에 시 주관 창업대회 입상한 거 가지고,\n그 스펙으로 컴공 가겠다고 뻐기던 거 맞네! 근데 왜?”", action: .text),
    Story(imageName: "2-2-0-14", dday: "D-100", title: "나", id: "2-2-0-14", nextId: "2-2-0-15", text: "“아, 아니.. 그냥 수시 지원 앞두고 궁금해져서…”", action: .text),
    Story(imageName: "2-2-0-15", dday: "D-100", title: "나", id: "2-2-0-15", nextId: "2-2-0-16", text: "“근데 걔가 수학을 잘하나봐?”", action: .text),
    Story(imageName: "2-2-0-16", dday: "D-100", title: "조력자 1", id: "2-2-0-16", nextId: "2-2-0-17", text: "“에이, 아닐걸? 내가 걔랑 1학년 때부터 같은 수학 학원 다니는데,\n걔 수학 1등급 한 번 받아보는 게 소원인 애야.”", action: .text),
    Story(imageName: "2-2-0-17", dday: "D-100", title: "조력자 1", id: "2-2-0-17", nextId: "2-2-0-18", text: "“이번 기말도 말아먹었는데, 겨우 2등급 받아서 걔네 아빠가 학원에 떡 돌렸어”", action: .text),
    Story(imageName: "2-2-0-18", dday: "D-100", id: "2-2-0-18", nextId: "2-2-0-19", text: "대체 이게 어떻게 된 상황이람..?", action: .text),
    Story(imageName: "2-2-0-19", dday: "D-100", id: "2-2-0-19", nextId: "2-2-0-20", text: "A는 학주와의 대화를 설명한다", action: .text),
    Story(imageName: "2-2-0-20", dday: "D-100", title: "조력자 1", id: "2-2-0-20", nextId: "2-2-0-21", text: "“A야.. 너 그거 조심해야해..\n딱봐도 운영위원장 아들 밀어주려고 하는 거잖아”", action: .text, sound: "한숨"),
    Story(imageName: "2-2-0-21", dday: "D-100", title: "조력자 1", id: "2-2-0-21", nextId: "2-2-0-22", text: "“내가 작년 선배들한테 이야기 들어서 아는데,\n학주가 자기 반 애들 서운대 더 보내려고 다른 반 담임들 조종하는 거로 유명해…”", action: .text),
    Story(imageName: "2-2-0-22", dday: "D-100", title: "조력자 1", id: "2-2-0-22", nextId: "2-2-0-23", text: "“운영위원장이랑 학주가 친한 거 알만 한 애들은 다 아는데…\n솔직히 빤하지 않아..?”", action: .text),
    Story(imageName: "2-2-0-23", dday: "D-100", title: "조력자 1", id: "2-2-0-23", nextId: "2-3-0-1", text: "“학주가 너한테 거짓말 한거야..”", action: .text, sound: "쿵"),
    Story(imageName: "2-3-0-1", dday: "D-97", title: "담임선생님", id: "2-3-0-1", nextId: "2-3-0-2", text: "“그래, A야. 고3 생활이 많이 힘들지?\n나한테 이야기하고 싶었다는 게 뭐니? 말해봐”", action: .text, gif: "2-3-0-1"),
    Story(imageName: "2-3-0-2", dday: "D-97", id: "2-3-0-2", nextId: "2-3-0-3", text: "A는 학주와의 대화를 설명한다", action: .text),
    Story(imageName: "2-3-0-3", dday: "D-97", title: "담임선생님", id: "2-3-0-3", nextId: "2-3-0-4", text: "“뭐? 이런 선생같지도 않은 인간이 다 있구나.\n소문으로만 듣긴 했는데, 학주의 개차반 인성이 사실이었구나”", action: .text, gif: "2-3-0-3", sound: "화남2"),
    Story(imageName: "2-3-0-4", dday: "D-97", title: "담임선생님", id: "2-3-0-4", nextId: "2-3-0-5", text: "“당장 고소할 준비를 해야겠구나.\n그때 대화를 녹음해둔 건 있니?”", action: .text),
    Story(imageName: "2-3-0-5", dday: "D-97", id: "2-3-0-5", nextId: "2-3-0-6", text: "이 정도로 일을 키울 건 아니었는데…?", action: .text),
    Story(imageName: "2-3-0-6", dday: "D-97", title: "나", id: "2-3-0-6", nextId: "2-3-0-7", text: "“아, 아니요.. 선생님 진정하시고요.\n저는 고소까지는 생각을 못하고 있었어요…”", action: .text),
    Story(imageName: "2-3-0-7", dday: "D-97", title: "담임선생님", id: "2-3-0-7", nextId: "2-3-0-8", text: "“그럴 수 있지. 원래 약자로 사는게 힘들지만, 그래도 정의가 죽을 수는 없어.\n선생님이 아는 기자들도 있어서 충분히 도와줄 수 있다.”", action: .text),
    Story(imageName: "2-3-0-8", dday: "D-97", id: "2-3-0-8", nextId: "2-3-0-9", text: "내가 원한 건 그냥 그대로 컴공을 쓰는 건데..\n입시 상담을 하고 싶었는데 이야기가 이상하게 흘러가네ㅠㅠ", action: .text),
    Story(imageName: "2-3-0-9", dday: "D-97", title: "나", id: "2-3-0-9", nextId: "2-3-0-10", text: "“선생님, 그럼 제가 어떻게 해야 좋을까요..?\n저는 정말 원래대로 서운대 컴공에 지원하고 싶어요”", action: .text),
    Story(imageName: "2-3-0-10", dday: "D-97", title: "담임선생님", id: "2-3-0-10", nextId: "2-3-0-11", text: "“우선 증거를 모아야겠지.\n앞으로 학주와 대화할 땐 항상 녹음기를 켜두고,\n또 그 동훈이라는 애의 수학 성적도 정식으로 요구해야겠..”", action: .text),
    Story(imageName: "2-3-0-11", dday: "D-97", title: "나", id: "2-3-0-11", nextId: "2-3-0-12", text: "“잠깐만요, 선생님. 고소를 하게 되면 학교 전체의 이미지가 떨어져요.\n수시에서 고등학교 네임벨류가 얼마나 중요한지 아시잖아요.”", action: .text),
    Story(imageName: "2-3-0-12", dday: "D-97", title: "나", id: "2-3-0-12", nextId: "2-3-0-13", text: "“수시 지원 과정에서 입시비리 있었던 고등학교라는 게 알려지면,\n저는 물론이고 수시 쓴 모든 학생들이 서류에서부터 떨어질거에요.”", action: .text),
    Story(imageName: "2-3-0-13", dday: "D-97", title: "담임선생님", id: "2-3-0-13", nextId: "2-3-0-14", text: "“A야, 그럼 다른 방법은 있니?\n네가 반격을 하지 않는다면 결국 너만 다른 과를 쓰게 될거야.”", action: .text),
    Story(imageName: "2-3-0-14", dday: "D-97", title: "담임선생님", id: "2-3-0-14", nextId: "2-3-0-15", text: "“만약 학주와 운영위원장 사이에 정말 모종의 거래가 오고갔다면,\n그 사람들은 필사적으로 너의 입시를 방해할거야.”", action: .text),
    Story(imageName: "2-3-0-15", dday: "D-97", id: "2-3-0-15", nextId: "2-3-0-16", text: "담임 선생님 말도 맞아...\n그 때 학주의 고집을 생각하면 절대 쉽게 물러나지 않을거야.\n어쩌면 다른 학교들 지원도 힘들어질거야", action: .text),
    Story(imageName: "2-3-0-16", dday: "D-97", title: "담임선생님", id: "2-3-0-16", nextId: "2-3-0-17", text: "“네가 공론화를 원한다면, 난 얼마든지 널 돕고싶구나.\n나도 학교의 미움을 받겠지만 그 정도는 내 학생을 위해 감수할 수 있다”", action: .text),
    Story(id: "2-3-0-17", action: .choice, question: "어떻게 해야할까?", choices: ["고소를 해야겠어. 이대로 억울하게 과를 바꿀 순 없어": "goso1", "그래도 고소는 너무 과격한 방법이야. 다른 방법을 찾아봐야겠어": "2-4-0-1"]),
    Story(id: "goso1", nextId: "goso", action: .text),
    Story(imageName: "2-4-0-1", dday: "D-92", title: "학년부장", id: "2-4-0-1", nextId: "2-4-0-2", text: "“그래, 결정은 했겠지?\n어떻게 하기로 했어?”", action: .text),
    Story(id: "2-4-0-2", action: .choice, question: "어떻게 말을 해야할까?", choices: ["운영위원장 아들 이야기로 한 번 떠본다": "2-4-1-1", "지원학과를 바꾸겠다고 말한다": "2-4-3-1"]),
    Story(imageName: "2-4-1-1", dday: "D-92", title: "나", id: "2-4-1-1", nextId: "2-4-1-2", text: "“선생님, 혹시 그 또 다른 서운대 컴공 지원자가 박동훈이던가요?”", action: .text),
    Story(dday: "D-92", id: "2-4-1-2", nextId: "2-4-1-3", text: "학년부장의 표정이 무섭게 바뀌었다.", action: .text, gif: "2-4-1-2", sound: "긴장감"),
    Story(imageName: "2-4-1-3", dday: "D-92", title: "학년부장", id: "2-4-1-3", nextId: "2-4-1-4", text: "“네가 어디서 뭘 들었는지는 모르겠다만,\n근거 없는 말을 퍼뜨리는 건 명예훼손이야.”", action: .text),
    Story(imageName: "2-4-1-4", dday: "D-92", title: "학년부장", id: "2-4-1-4", nextId: "2-4-1-5", text: "“학생이 선생에게 의심만 많고 이렇게나 존경심이 없다니,\n네 학교장 추천 이야기는 다시 생각해봐야 할 수도 있겠구나.”", action: .text),
    Story(id: "2-4-1-5", action: .choice, question: "어떻게 해야할까?", choices: ["녹음기를 꺼내며 동훈이 이야기를 직접적으로 물어본다": "2-4-2-1", "잘못했다고 말씀드리고 지원학과를 바꾸겠다고 한다": "2-4-3-1"]),
    Story(imageName: "2-4-2-1", dday: "D-92", title: "나", id: "2-4-2-1", nextId: "2-4-2-2", text: "“선생님, 유언비어가 아니에요. 제가 어제 동훈이를 찾아가서 직접 물어봤거든요\n자기가 서운대 컴공을 쓴다고 말해줬어요.”", action: .text),
    Story(imageName: "2-4-2-2", dday: "D-92", title: "나", id: "2-4-2-2", nextId: "2-4-2-3", text: "“여기 녹음해 온 내용 있어요”", action: .text),
    Story(imageName: "2-4-2-3", dday: "D-92", id: "2-4-2-3", nextId: "2-4-2-4", text: "학주는 가만히 녹음된 내용을 듣는다.\n서운대 컴퓨터공학과를 지원한다고 말하는 동훈의 목소리가 녹음되어 있었다.", action: .text),
    Story(imageName: "2-4-2-4", dday: "D-92", title: "학년부장", id: "2-4-2-4", nextId: "2-4-2-5", text: "“끙...”", action: .text),
    Story(imageName: "2-4-2-5", dday: "D-92", title: "나", id: "2-4-2-5", nextId: "2-4-2-6", text: "“선생님, 그러면 이제 박동훈 걔 수학 내신 성적 알려주세요.\n지망학과를 바꾸는 중대한 결정을 하기 전에 그 정도는 알아야 할 거 같아서요.”", action: .text),
    Story(imageName: "2-4-2-6", dday: "D-92", id: "2-4-2-6", nextId: "2-4-2-7", text: "진짜 무슨 거래가 있었나보네.. 날 죽일듯이 노려보네.", action: .text),
    Story(imageName: "2-4-2-7", dday: "D-92", title: "학년부장", id: "2-4-2-7", nextId: "2-4-2-8", text: "“됐다. 나가라.\n없던 이야기로 해라.”", action: .text),
    Story(imageName: "2-4-2-8", dday: "D-92", title: "나", id: "2-4-2-8", nextId: "2-4-2-9", text: "“네? 왜요?\n동훈이가 저보다 수학 내신이 얼만큼 좋은 건데요?”", action: .text),
    Story(imageName: "2-4-2-9", dday: "D-92", title: "학년부장", id: "2-4-2-9", nextId: "2-4-2-10", text: "“나가! 나가래도!\n너 같은 버르장머리 없는 학생은 내 교사인생 20년 중 처음이구나!”", action: .text, gif: "2-4-2-9", sound: "화남1"),
    Story(imageName: "2-4-2-10", dday: "D-92", id: "2-4-2-10", nextId: "2-4-2-11", text: "학년부장의 고성에 교무실의 다른 선생들이 일제히 A를 쳐다보고 수군댄다.", action: .text),
    Story(imageName: "2-4-2-11", dday: "D-92", title: "학년부장", id: "2-4-2-11", nextId: "2-4-2-12", text: "“이봐요 3반 담임. 대체 반 애들 교육을 어떻게 하는 거야?\n어떻게 학생이 선생님에게 눈을 치켜뜨고 협박을 해?”", action: .text, gif: "2-4-2-9.gif", sound: "화남1"),
    Story(imageName: "2-4-2-12", dday: "D-92", id: "2-4-2-12", nextId: "2-4-2-13", text: "협박이라는 단어에 다른 선생들의\n수군거리는 소리가 커진다.", action: .text, sound: "웅성거림"),
    Story(imageName: "2-4-2-13", dday: "D-92", title: "담임선생님", id: "2-4-2-13", nextId: "2-4-2-14", text: "“선생님, 여기서 더 큰소리 내셔야 좋을 거 없을 듯 합니다.\nA야, 얼른 반으로 올라가거라.”", action: .text, gif: "2-4-2-11.gif", sound: "쿵"),
    Story(imageName: "2-4-2-14", dday: "D-92", title: "담임선생님", id: "2-4-2-14", nextId: "2-4-2-15", text: "“어떻게 된거니? 학주가 저렇게나 흥분하고.”", action: .text),
    Story(imageName: "2-4-2-15", dday: "D-92", title: "나", id: "2-4-2-15", nextId: "2-4-2-16", text: "“동훈이 이야기를 꺼냈더니 저러셨어요.\n동훈이의 수학 성적을 직접적으로 여쭤봤거든요.”", action: .text),
    Story(imageName: "2-4-2-16", dday: "D-92", title: "나", id: "2-4-2-16", nextId: "2-4-2-17", text: "“선생님, 근데 저 학주와의 대화 다 녹음했어요.\n선생님이 저번에 말씀하신대로요.”", action: .text),
    Story(imageName: "2-4-2-17", dday: "D-92", title: "나", id: "2-4-2-17", nextId: "2-4-2-18", text: "“그래도 대입 끝날때까지는 조용히 지내고 싶어요.\n제 입시도, 친구들의 입시도 걸려 있으니까요.”", action: .text),
    Story(imageName: "2-4-2-18", dday: "D-92", title: "나", id: "2-4-2-18", nextId: "2-4-2-19", text: "“그렇지만 혹시나 또 학주가 절 협박하는 일이 있을까봐 녹음은 해두었어요\n아마 이 일이 있고나서 학주가 절 가만두지는 않을 거 같아서요”", action: .text),
    Story(imageName: "2-4-2-19", dday: "D-92", title: "담임선생님", id: "2-4-2-19", nextId: "3-1-1", text: "“그래. 잘했다.\n선생님 도움이 필요하면 언제든지 말하렴. 난 항상 네 편이야.”", action: .text),
    Story(imageName: "2-4-3-1", dday: "D-92", title: "학년부장", id: "2-4-3-1", nextId: "2-4-3-2", text: "“그래. 아주 잘 생각했다. 다 너를 위한 거야.\n그리고 대학 가서도 복수전공 할 수도 있어. 일단 서운대에는 들어가야지.”", action: .text, sound: "웃음"),
    Story(imageName: "2-4-3-2", dday: "D-92", title: "학년부장", id: "2-4-3-2", nextId: "2-4-3-3", text: "“뭐 또 별다른 어려움은 없니?”", action: .text),
    Story(imageName: "2-4-3-3", dday: "D-92", title: "나", id: "2-4-3-3", nextId: "2-4-3-4", text: "“그.. 학교장 추천 말인데요..\n고연대 학교장 추천은 대대로 전교 2등이 받는 다고는 들어왔는데..\n아직 교장선생님이 확답을 안주셔서요”", action: .text),
    Story(imageName: "2-4-3-4", dday: "D-92", title: "학년부장", id: "2-4-3-4", nextId: "2-4-3-5", text: "“으응? 아, 그거?\n그거 선생님이 교장선생님께 말씀드려서 내일 중으로 확정되게 하마”", action: .text),
    Story(imageName: "2-4-3-5", dday: "D-92", title: "학년부장", id: "2-4-3-5", nextId: "3-1-1", text: "“고연대 학교추천은 당연히 A, 네가 받아야지.\n그럼 우리, 끝까지 잘해보자 허허허”", action: .text, sound: "웃음")
]
